export class DiscountToModel {
    // discountId: string;
    // performId: string;
    // seatId: string;
    // discountType: string;
    // noOfDiscountSeat: number;
    // discountValue: number;
    // discountAuto: string;
    // discountLimitType: string;
    // discountPercent: number;
    // discountConditionType: string;

    discountId: string;
    discountName: string;
    discountType: string;
    discountLimit: number;
    discountLimitType: string;
    discountRemainning: number;
    discountPercent: number;
    discountConditionType: string;
    discountCondition: string;
    discountAmount: number;
    discountAllround: string;
    discountAllZone: string;
    discountAllSeat: string;
    ticketBuy: number;
    ticketFree: number;
    detail: string;
    allChannnel: string;
    channelPos: string;
    channelWeb: string;
    channelAgent: string;
    permember: number;
    promotionCode: string;
    sponsorId: string;
    sponsorName: string;
    sponsorLogo: string;
    inputlabel: string;
    MemberIdSizeMin: string;
    MemberIdSizeMax: string;
    performId: string;
    performName: string;
    roundId: string;
    zoneId: string;
    zoneType: string;
    effectiveDate: Date;
    expireDate: Date;
    activeflag: string;
    autoflag: string;
    updateBy: string;
    discountBillAmt: number;
    covenienceFee: number;
    billAmt: number;
    discountValue: number;
}